# Generated by Django 6.1 on 2026-08-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='type_car',
            field=models.CharField(choices=[('passenger_cars', 'легоковые'), ('cargo', 'грузовой'), ('motorbike', 'мотоцикл')], default=1, verbose_name='Тип машины'),
            preserve_default=False,
        ),
    ]
