# Generated by Django 6.1 on 2026-08-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_type_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('raiting', models.IntegerField(choices=[(1, '⚡️'), (2, '⚡️⚡️'), (3, '⚡️⚡️⚡️'), (4, '⚡️⚡️⚡️⚡️'), (5, '⚡️⚡️⚡️⚡️⚡️')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='auto.auto', verbose_name='Автомобиль')),
            ],
        ),
    ]
