# Generated by Django 6.1 on 2026-09-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_carreview_car_alter_carreview_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=' Называние модли ')),
                ('year', models.IntegerField()),
                ('description', models.CharField(verbose_name='История')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.AlterModelOptions(
            name='carreview',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterField(
            model_name='carreview',
            name='text',
            field=models.TextField(verbose_name='Оценка'),
        ),
    ]
