# Generated by Django 6.1 on 2026-09-07 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_brand_alter_carreview_options_alter_carreview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='auto.brand'),
            preserve_default=False,
        ),
    ]
