# Generated by Django 6.1 on 2026-09-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_carreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreview',
            name='user',
        ),
    ]
